Promo:
  detail_pages:
    - url: "https://www.banksinarmas.com/id/promosi"
      title: "Semua Promo"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-shabu-jin"
      title: "Promo Shabu Jin"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-magal-korean-bbq"
      title: "Promo Magal"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-jin-ramen"
      title: "Promo Jin Ramen"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-form-the-sea"
      title: "Promo From the Sea"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-8treasures"
      title: "Promo 8 Treasures"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-8treasures-noodle-house"
      title: "Promo 8 Treasures Noodle House"
    - url: "https://www.banksinarmas.com/id/promosi/snk-gionsushi"
      title: "Promo Gion Sushi"
    - url: "https://www.banksinarmas.com/id/promosi/snk-nob"
      title: "Promo NOB Cafée & Patisserie"
    - url: "https://www.banksinarmas.com/id/promosi/snk-weenamkee"
      title: "Promo Wee Nam Kee"
    - url: "https://www.banksinarmas.com/id/promosi/brastagi-supermarket"
      title: "Promo Supermarket Brastagi"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-putien-restaurant"
      title: "Promo Putien"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-xxi"
      title: "Promo XXI Bioskop"
    - url: "https://www.banksinarmas.com/id/promosi/gojek-saturday-visa"
      title: "Promo Gojek"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-may-star-restaurant"
      title: "Promo May Star"
    - url: "https://www.banksinarmas.com/id/promosi/kk-bicester-collection"
      title: "Promo Bicester Collection"
    - url: "https://www.banksinarmas.com/id/promosi/kk-marhen-j"
      title: "Promo Marhen J"
    - url: "https://www.banksinarmas.com/id/promosi/kk-qris-mcd"
      title: "Promo QRIS McDonald's"
    - url: "https://www.banksinarmas.com/id/promosi/kk-pizza-hut"
      title: "Promo Pizza Hut"
    - url: "https://www.banksinarmas.com/id/promosi/kk-grand-mansion"
      title: "Promo Grand Mansion"
    - url: "https://www.banksinarmas.com/id/promosi/kk-sushi-manna"
      title: "Promo Sushi Manna"
    - url: "https://www.banksinarmas.com/id/promosi/buka-deposito-online"
      title: "Promo Buka Deposito Online"
    - url: "https://www.banksinarmas.com/id/promosi/buka-tabungan-simpel"
      title: "Promo Buka Tabungan Simpel"
    - url: "https://www.banksinarmas.com/id/promosi/pijat-chien-khang-thang-thai-reflexology"
      title: "Promo Chien Khang Thang Pijat Thai Reflexology"
    - url: "https://www.banksinarmas.com/id/promosi/jumpstart-ngopi-hemat"
      title: "Promo QRIS Jumpstart Ngopi Hemat"
    - url: "https://www.banksinarmas.com/id/promosi/diskon-angke-restaurant"
      title: "Promo Angke"

Produk:
  detail_pages:
    - url: "https://www.banksinarmas.com/id/personal/produk/simpanan"
      title: "Produk Simpanan"
    - url: "https://www.banksinarmas.com/id/personal/produk/kartukredit"
      title: "Produk Kartu Kredit"
    - url: "https://www.banksinarmas.com/id/personal/produk/kartukredit/kartu-kredit-indigo"
      title: "Kartu Kredit Personal 'Silver Indigo'"
    - url: "https://www.banksinarmas.com/id/personal/produk/kartukredit/kartu-kredit-alfamart"
      title: "Kartu Kredit Personal 'Silver Alfamart'"
    - url: "https://www.banksinarmas.com/id/personal/produk/kartukredit/kartu-kredit-personal"
      title: "Kartu Kredit Personal 'Platinum'"
    - url: "https://www.banksinarmas.com/id/bisnis/produk/pinjaman/kartu-kredit-korporat"
      title: "Kartu Kredit Korporat 'Platinum'"
    - url: "https://www.banksinarmas.com/id/personal/produk/reksadana"
      title: "Produk Reksadana"
    - url: "https://www.banksinarmas.com/id/personal/produk/bancasurance"
      title: "Produk Bancasurance"
    - url: "https://www.banksinarmas.com/id/personal/produk/pinjaman"
      title: "Produk Pinjaman"

Kurs Mata Uang:
 detail_pages:
    - url: "https://www.banksinarmas.com/id/kurs"
      title: "Info Kurs"

Profil Bank Sinarmas:
 detail_pages:
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/profil-bank-sinarmas"
      title: "Profil Bank Sinarmas"

Manajemen Bank Sinarmas:
 detail_pages:
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/managemen-bank-sinarmas"
      title: "Manajemen Bank Sinarmas"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/tjendrawati-Widjaja"
      title: "Presiden Komisaris"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/sammy-kristamuljana"
      title: "Komisaris Independen"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/rusmin"
      title: "Komisaris Independen"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/frenky-tirtowijoyo"
      title: "Direktur Utama Bank Sinarmas"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/miko-andidjaja"
      title: "Direktur"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/ekajaya-ongny-putra"
      title: "Direktur"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/enny-kamal"
      title: "Direktur"
    - url: "https://www.banksinarmas.com/id/informasiumum/tentangkami/sendy"
      title: "Direktur"
    
    
